### ISSUE TITLE
DaVinci Resolve Recipes

### ISSUE THREAD

**Issue by nstrauss** [davidschoefberger/autopkg-recipes#1]
Hey @davidschoefberger, would you consider reverting commit bf00b53b0eb8a825214226da0d1dfa523b4a6af6? We were using the DaVinci Resolve recipes and found them to be working well enough for our use case. Thank you for having written them in the first place.

If you're not interested in maintaining the recipes I could migrate them over to my autopkg repo. Thanks.

**Comment by davidschoefberger** [comment]
Hi @nstrauss,

sure - just reverted it! How do you use them? Since in the current state they did not work in the past.

**Comment by nstrauss** [comment]
Ha. Long as the registration info is there it's been pulling the latest version. Coming into this from someone else having set up the recipe. Been working as long as I can tell. Thanks for reverting. If it breaks in the future I can submit a PR.
